# Generated by Django 4.2.7 on 2023-11-23 20:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Jobseeker', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobseekerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=30)),
                ('DOB', models.DateField(null=True)),
                ('qualification', models.CharField(max_length=120)),
                ('skills', models.CharField(max_length=100)),
                ('experience', models.PositiveIntegerField()),
                ('cv', models.FileField(null=True, upload_to='files')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='jobseeker', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='applications',
            name='candidate',
        ),
        migrations.DeleteModel(
            name='CandidateProfile',
        ),
        migrations.AddField(
            model_name='applications',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Jobseeker.jobseekerprofile'),
        ),
    ]
